#!/bin/sh

docker-compose up -d --build

echo "Example configuration:"
echo "-> docker-compose exec kafka kafka-console-producer --broker-list kafka:9093 --producer.config /etc/kafka/consumer.properties --topic test"
echo "-> docker-compose exec kafka kafka-console-consumer --bootstrap-server kafka:9093 --consumer.config /etc/kafka/consumer.properties --topic test --from-beginning"




docker exec kafka_a kafka-topics --bootstrap-server kafka_a:29092 --create --topic __consumer_timestamps --partitions 3 --replication-factor 1
docker exec kafka_a kafka-topics --bootstrap-server kafka_a:29092 --create --topic topic.topic.source --partitions 3 --replication-factor 1

docker exec kafka_a kafka-topics --bootstrap-server kafka_b:29093 --create --topic source.in --partitions 3 --replication-factor 1
docker exec kafka_a kafka-topics --bootstrap-server kafka_b:29093 --create --topic topic.topic.source --partitions 3 --replication-factor 1


# docker-compose  exec kafka_a /opt/kafka/bin/kafka-console-producer.sh  --broker-list kafka_a:29092 --topic topic-topic-source

# docker exec kafka_b kafka-topics --bootstrap-server kafka_b:29093 --list